require 'src.engine.components.Collidable'
require 'src.engine.components.Drawable'
require 'src.engine.components.Moveable'
require 'src.engine.components.Position'
require 'src.engine.components.Light'
require 'src.engine.components.ParentPositionOffset'
require 'src.engine.components.Player'
require 'src.engine.components.Logic.IsCamera'